Tp3 - Définition de l'objet du document
vladimirkosmala/tp-inpulse pull request #49
Opened 2019-12-19 14:40 UTC by cristianemenna

2019-12-19 14:45 UTC, nach0cheese requested changes
Fais attention a la formatation du paragraphe Cris ;)

2019-12-19 14:47 UTC, cristianemenna commented
Merci, c'est corrigé !

2019-12-19 14:49 UTC, nach0cheese approved these changes
Yay =)

2019-12-20 08:47 UTC, LoisCoulon approved these changes
¡muy bien!

2019-12-20 08:58 UTC, merged