TP3 - description de git pull
vladimirkosmala/tp-inpulse pull request #60
Opened 2019-12-20 14:30 UTC by fokoua

2019-12-20 14:36 UTC, cristianemenna requested changes
Marcellin, juste un détail : le git pull correspond au point 11 du fichier. Pour toi c'est plutôt par rapport à pull request ;)

2019-12-20 14:48 UTC, fokoua commented
merci pour la remarque chris :) je vien de changer

2019-12-20 14:48 UTC, cristianemenna approved these changes
Merci, c'est parfait maintenant. J'approuve.

2019-12-21 18:30 UTC, LegrasSarah approved these changes
Impec, moi je vois aucunes fautes d'orthographe

2019-12-21 18:31 UTC, merged